direction: right
entry point -> input -> new game -> Game Loop.move elements

Game Loop: {
  move elements -> detect collision
  detect collision -> no collision -> move elements
  detect collision -> collision detected -> _.game over

  input -> give bird lift
}

game over -> input
