# This game loop is a simplified overview and inaccurate of the details of
# the actual game loop.

direction: right
entry point -> wait input -> new game
new game -> Game Loop.move elements
new game -> Game Loop.wait input

Game Loop: {
  move elements -> detect collisions
  detect collisions -> no collision -> wait -> move elements
  detect collisions -> collision detected -> _.game over

  wait input -> give bird lift -> wait input
}

game over -> wait input
